<!Doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Calgary Attached ... semis, freehold townhouses">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
        <style>
            .row.container{
                margin-top: 30px;
            }
            .blockquote:before
            {
                content: '\201C';
            }

            .blockquote:after
            {
                content: '\201D';
            }
        </style>
    </head>
    <body>
        <div class="row container">
            <div class="col-md-7"></div>
            <div class="col-md-5">
                <div class="jumbotron">
                    <h1>Heading</h1>
                    <p class="blockquote">Tagline</p>
                    <p>
                        <a class="btn btn-primary btn-large center-block" data-toggle="modal" data-target="#modal1">
                            Learn more
                        </a>
                    </p>
                </div>
                <div class="jumbotron">
                    <h1>Heading</h1>
                    <p class="blockquote">Tagline</p>
                    <p>
                        <a class="btn btn-primary btn-large center-block" data-toggle="modal" data-target="#modal1">
                            Learn more
                        </a>
                    </p>
                </div>
                <div class="jumbotron">
                    <h1>Heading</h1>
                    <p class="blockquote">Tagline</p>
                    <p>
                        <a class="btn btn-primary btn-large center-block" data-toggle="modal" data-target="#modal1">
                            Learn more
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <div id="modal1" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <form>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="inputEmail">Email</label>
                                <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <label for="inputPassword">Password</label>
                                <input type="password" class="form-control" id="inputPassword" placeholder="Password">
                            </div>
                            <div class="checkbox">
                                <label><input type="checkbox"> Remember me</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button id="modalform1submit" type="submit" class="btn btn-default" data-dismiss="modal">Submit</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
        <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script>
            jQuery("#modalform1submit").click(function(){
                alert("thanks");
                return false;
            });

        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </body>
</html>
